### ISSUE TITLE
Web interface of Octoprint crashes

### ISSUE THREAD

**Issue by babylongithub0815** [fieldOfView/Cura-OctoPrintPlugin#108]
Web interface of Octoprint can no longer be used when you press the button "house" in Cura, go to zero position.

Weboberfläche von Octoprint lässt sich nicht mehr bedienen wenn man in Cura auf den Button "Haus" drückt, für gehe in Null Position.

**Comment by fieldOfView** [comment]
Can you be a little more specific? What do you mean by "can no longer be used"? What happens when you try? 

Does the same button in the OctoPrint web interface work as expected?

What printer do you use?

**Comment by incrediblesolutions** [comment]
having a similar issue with a fresh install.  going to reinstall as finding documentation of the code seems to be difficult.  i would like to find a wikki or doc web site that has full documentation of what the Octopi Part is

**Comment by fieldOfView** [comment]
Before you ask documentation from me, might I be so bold to ask you to actually describe your problem to me? All you say is that you have a "similar" problem to a problem where I said I need more information to be able to help. How do you expect me to know what is going wrong?

**Comment by fieldOfView** [comment]
Closing due to lack of information.
