### ISSUE TITLE
Support multiple printers

### ISSUE THREAD

**Issue by steevegldev** [fieldOfView/Cura-OctoPrintPlugin#111]
Have 2 printers, one is USB, the second is OctoPrint.

Actually in Cura 4.0, only the fist alphabetical print has the plugin setting.

USB Printer:
![image](https://user-images.githubusercontent.com/6455947/55280081-01ac9c80-52f7-11e9-9ee7-bcbfd9338bee.png)

OctoPrint printer:
![image](https://user-images.githubusercontent.com/6455947/55280085-06715080-52f7-11e9-9ac5-9dbefd5536c8.png)

Cura 4.0
OctoPrint Connection 4.9

**Comment by fieldOfView** [comment]
Only the currently active printer can be fully configured in Cura. See the “Activate” button. This is equivalent to switching to that printer in the main Cura interface.
