### ISSUE TITLE
ETA On Octoprint

### ISSUE THREAD

**Issue by AfroPsycho** [fieldOfView/Cura-OctoPrintPlugin#125]
Hey
I have a plugin that calculates ETA for the print on octoprint
Because of print directly starting from cura 
There is no time for other plugin to calculate before print starts
So it calculates while printing

I want to ask if there is a way to choose upload to OctoPrint instead of Print

**Comment by fieldOfView** [comment]
In the "Connect to OctoPrint" dialog, there is an checkbox labeled "Automatically start print job after uploading", which is selected by default. Does deselecting this work for you?

**Comment by AfroPsycho** [comment]
I wasn't know that option before
I will check it as soon as possible
Thanks for the help

Best regards,
Bora Hoşadam

Aldo Hoeben <notifications@github.com> şunları yazdı (17 Ağu 2019 14:53):

﻿

In the "Connect to OctoPrint" dialog, there is an checkbox labeled "Automatically start print job after uploading", which is selected by default. Does deselecting this work for you?
