### ISSUE TITLE
Monitor page in Cura doesn't show actual printing time estimates

### ISSUE THREAD

**Issue by hapklaar** [fieldOfView/Cura-OctoPrintPlugin#127]
The PintTimeGenius plugin in Octoprint makes printing time estimation a lot more accurate. 

However it seems printing time estimates shown on the OctoPrintPlugin Monitor page are derived from a different value (?)

For example, I'm printing a calibration cube, which is estimated to take 12 minutes by PrintTimeGenius. Monitor page shows 28 hours, then 16 hours, then 2 hours, etc. Way off, up until the end of printing.

Could the OctoPrintPlugin be made to show the time that is shown in OctoPrint itself, which is very accurate when using the specified plugin?

![image](https://user-images.githubusercontent.com/7703320/65436110-e5129c80-de21-11e9-9551-bbcdbc6a1343.png)

**Comment by fieldOfView** [comment]
The plugin shows the data it gets from the OctoPrint API. I have not used PrintTimeGenius, so I don't know if there is a different way for the plugin to get progress data if that plugin is running.
