### ISSUE TITLE
[Feature-Request] Sending UltimakerFormatPackage (.ufp) to OcotoPrint

### ISSUE THREAD

**Issue by OllisGit** [fieldOfView/Cura-OctoPrintPlugin#132]
First: Thanks a lot for you Plugin!!!

I saw the "[OctoPrint-UltimakerFormatPackage-Plugin](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage)" from jneilliii and I was thinking about sending the ufp-file directly to the printer instead of the gcode.
Is this feature on your roadmap? 
If not, do you think it is possible to implement and maybe you have same tips how to implement this.

Thx, in advance
Olli

**Comment by fieldOfView** [comment]
It is not on the roadmap; it is already implemented. The Cura plugin should automatically detect the UFP plugin is installed and send ufp files instead of gcode.
