### ISSUE TITLE
Octoprint 1.4.0 RC3 - Printer is Offline

### ISSUE THREAD

**Issue by Deneteus** [fieldOfView/Cura-OctoPrintPlugin#138]
Issue: Octoprint 1.4.0 RC3 broke the ability to send files from Cura. Worked in 1.4.0RC2.
It shows that Cura is connected in the printer dialog but the printer error says it's offline.

![image](https://user-images.githubusercontent.com/6380390/70774175-14f58000-1d3f-11ea-88fb-1bbb6ac514f7.png)

![image](https://user-images.githubusercontent.com/6380390/70774187-1cb52480-1d3f-11ea-8383-0da33cb4fc58.png)

I left some feedback here: 
https://github.com/foosel/OctoPrint/issues/3389

**Comment by fieldOfView** [comment]
> It shows that Cura is connected in the printer dialog but the printer error says it's offline.

To clarify: the Connect to OctoPrint dialog says that Cura is connected to OctoPrint. The error message is OctoPrint saying it is not connected to the printer. Please confirm in the OctoPrint web interface that the printer is "connected" and that you can eg jog the head using the controls on the control tab.

**Comment by Deneteus** [comment]
> > It shows that Cura is connected in the printer dialog but the printer error says it's offline.
> 
> To clarify: the Connect to OctoPrint dialog says that Cura is connected to OctoPrint. The error message is OctoPrint saying it is not connected to the printer. Please confirm in the OctoPrint web interface that the printer is "connected" and that you can eg jog the head using the controls on the control tab.

I can indeed Jog the head of the printer and preheat.

![image](https://user-images.githubusercontent.com/6380390/70821795-9bdb4480-1da1-11ea-9915-804ab5f8417e.png)

**Comment by fieldOfView** [comment]
When it happens again, please open http://octopi.local/api/printer?apikey=yourapikey in a browser and post the response here.

**Comment by fieldOfView** [comment]
Has this ever happened again?

**Comment by fieldOfView** [comment]
I need a Cura.log to know what is going on. See Help -> Show configuration folder. Please upload cura.log somewhere and post a link here (as the file may be sizeable).

**Comment by fieldOfView** [comment]
I'm going to close this issue because of lack of activity, but I think it is the same underlying issue as #136 which I'll leave open for now. Cura seems to somehow loose its connection and stop updating the status of OctoPrint.
