### ISSUE TITLE
cura-plugin-octoprint not in ppa:thopiekar/cura

### ISSUE THREAD

**Issue by colinl** [fieldOfView/Cura-OctoPrintPlugin#140]
On Ubuntu 19.10, trying to install from the ppa as suggested, using
sudo apt install cura-plugin-octoprint
but it seems that the package does not exist in the ppa.  I am accessing the ppa ok as it is picking Cura up from there.

**Comment by fieldOfView** [comment]
I don’t maintain that repository, so there is nothing I can do about it. Please install the plugin through the Marketplace.

**Comment by colinl** [comment]
Thanks, I have installed it through the marketplace, I thought perhaps you would like to know so as to correct the instructions.

**Comment by fieldOfView** [comment]
I have removed the instruction about the ppa from the readme. Thanks.
