### ISSUE TITLE
Minor Windows 10 Pop-Up Issue

### ISSUE THREAD

**Issue by jneilliii** [fieldOfView/Cura-OctoPrintPlugin#160]
The windows 10 pop up shows html code as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/5249455/76978540-34d3ab80-690d-11ea-8121-c86c766e65ba.png)

**Comment by fieldOfView** [comment]
I'll look in to it. The same message probably shows if you restore the Cura window.

**Comment by jneilliii** [comment]
Cura side appears "normal".

![image](https://user-images.githubusercontent.com/5249455/76980510-a7458b00-690f-11ea-816a-8741a58835ef.png)

**Comment by fieldOfView** [comment]
Well, ideally that should also show something more helpful.

**Comment by fieldOfView** [comment]
To reproduce this, you shut down OctoPrint while Cura was connected to it? Did you use a "discovered" instance, or did you use an instance that was Added manually in the Connect to OctoPrint dialog?

**Comment by jneilliii** [comment]
It happens when I'm connected to a manually added instance and restart octoprint as a result of plugin install for example.

**Comment by jneilliii** [comment]
I was able to catch a screenshot of it in cura...

![image](https://user-images.githubusercontent.com/5249455/76988374-fa710b00-691a-11ea-934b-d69e7a499af3.png)

**Comment by fieldOfView** [comment]
Fixed in master with the above commit.

See de34fb1.
