### ISSUE TITLE
Automatically connect or prompt if you would like to connect

### ISSUE THREAD

**Issue by meme8383** [fieldOfView/Cura-OctoPrintPlugin#162]
It would be nice if Cura would automatically connect to the printer or ask me if I would like to connect because I would like to be able to turn on my printer and click "print" instead of waiting for the octoprint website to open and clicking connect.

**Comment by fieldOfView** [comment]
This should not be too hard to implement after the smart power plug support already paved the way. Note to self: https://docs.octoprint.org/en/master/api/connection.html#issue-a-connection-command

**Comment by fieldOfView** [comment]
See https://github.com/fieldOfView/Cura-OctoPrintPlugin/commit/24c17ab39650d533cad0ac33ec3fee13b3ea99c0

**Comment by fieldOfView** [comment]
Version 3.5.13 is now available in the Marketplace.
