### ISSUE TITLE
Domoticz Power, working but doesn't initiate Connect

### ISSUE THREAD

**Issue by Wob76** [fieldOfView/Cura-OctoPrintPlugin#164]
Running Cura 4.5 and the Connect to OctoPrint 3.5.12

I am linking in to the OctoPrint-Domoticz plugin and the power option is populated and working, the issue I am seeing is that it doesn't initiate a connect after the power up. I have the Domoticz plugin configured to "Auto Connect" and GCODE on Delay, I have also tried adjusting the delays without change. The plugin does work as expected when using the Octoprint plugin Power Icon, or inserted start GCODE.

I wasn't sure if to open an issue here or with the OctoPrint-Domoticz plugin, but since it works as expected from the Octoprint Interface and GCODE I thought it best placed here.

**Comment by Wob76** [comment]
Sorry, after having a better look I see #162 is a similar request, please feel free to link and close this one.

**Comment by fieldOfView** [comment]
Does OctoPrint initiate the connection if you turn on the power from within the OctoPrint web interface?

**Comment by fieldOfView** [comment]
@jneilliii, could it be that autoConnect works in the Domoticz plugin when the plug is turned on via the button in the interface (ie: from js) but not when turning the plug on through the API (ie: from python)?

**Comment by fieldOfView** [comment]
Looking at the code of the Domoticz plugin, it looks like that plugin completely ignores its own autoConnect setting when turning the plug on through the API. I would say this is a bug with that plugin.

**Comment by Wob76** [comment]
Thank you for looking so quickly, I'll raise a ticket over there.
