### ISSUE TITLE
Error file not found on sd card

### ISSUE THREAD

**Issue by devildant** [fieldOfView/Cura-OctoPrintPlugin#175]
Hello,

I note a small bug with the last version, an error is raised systematically ("Error file not found..."), when the option "store gcode on the printer sd card" is activated.

![image](https://user-images.githubusercontent.com/8700106/84221376-622b9200-aad5-11ea-8173-01656aca18c2.png)

cura 4.6.1
plugin version : 3.5.14
![image](https://user-images.githubusercontent.com/8700106/84218071-00b3f500-aace-11ea-9d20-d58ff853468b.png)

**Comment by fieldOfView** [comment]
Thanks for the report. I'll try to find out what is going wrong.
 
Could you try if the error also happens if you have the "Automatically start print job after uploading" option selected?

**Comment by devildant** [comment]
hello, I tell you after my print in 7 hours :)

**Comment by devildant** [comment]
I was able to test, same error with the ""Automatically start print job after uploading" option activated (the print starts well), so it's also a false positive
