### ISSUE TITLE
Flip camera horizontally/vertically not working

### ISSUE THREAD

**Issue by JamieS01** [fieldOfView/Cura-OctoPrintPlugin#180]

**Comment by fieldOfView** [comment]
The OctoPrint Connection plugin applies the same flips and rotation that is configured in OctoPrint. Is your camera showing in the right orientation in the OctoPrint webinterface?

**Comment by JamieS01** [comment]
> The OctoPrint Connection plugin applies the same flips and rotation that is configured in OctoPrint. Is your camera showing in the right orientation in the OctoPrint webinterface?

It shows correctly in the octoprint interface, but not in the plugin.

**Comment by fieldOfView** [comment]
Please visit `http://[address of your octoprint instance]/api/settings?apikey=[your api key]` and post the `webcam` section of the file you get, which looks like this:

![image](https://user-images.githubusercontent.com/143551/86526683-51352d00-be97-11ea-8dec-c83d128bfa95.png)

**Comment by JamieS01** [comment]
{"api":{"allowCrossOrigin":false,"key":"3E2674A51FB34DF2B01226BB3C0C9FEE"},"appearance":{"closeModalsWithClick":true,"color":"orange","colorIcon":true,"colorTransparent":false,"defaultLanguage":"_default","fuzzyTimes":true,"name":"Ender 3","showFahrenheitAlso":false},"feature":{"autoUppercaseBlacklist":["M117","M118"],"g90InfluencesExtruder":false,"gcodeViewer":true,"keyboardControl":true,"mobileSizeThreshold":2097152,"modelSizeDetection":true,"pollWatched":false,"printCancelConfirmation":true,"printStartConfirmation":false,"sdSupport":true,"sizeThreshold":20971520,"temperatureGraph":true},"folder":{"logs":"/home/pi/.octoprint/logs","timelapse":"/home/pi/.octoprint/timelapse","timelapseTmp":"/home/pi/.octoprint/timelapse/tmp","uploads":"/home/pi/.octoprint/uploads","watched":"/home/pi/.octoprint/watched"},"gcodeAnalysis":{"runAt":"idle"},"plugins":{"BLTouch":{"cmdProbeBed":"G29","cmdProbeDown":"M280 P0 S10","cmdProbeUp":"M280 P0 S90","cmdReleaseAlarm":"M280 P0 S160","cmdSaveSettings":"M500","cmdSelfTest":"M280 P0 S120","confirmation":true},"HeaterTimeout":{"enabled":true,"interval":15,"notifications":true,"timeout":1800},"PrintTimeGenius":{"allowAnalysisWhileHeating":true,"allowAnalysisWhilePrinting":false,"analyzers":[{"command":"\"/home/pi/oprint/bin/python2\" \"/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py\" \"{gcode}\"","description":"All gcode analyzers (usually not as good as marlin-calc)","enabled":false},{"command":"\"/home/pi/oprint/bin/python2\" \"/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py\" marlin-calc \"{gcode}\" \"{mcodes}\"","description":"Marlin firmware simulation (replaces Octoprint built-in, faster and more accurate)","enabled":true},{"command":"\"/home/pi/oprint/bin/python2\" \"/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py\" \"{gcode}\" --parsers slic3r_pe_print_time slic3r_pe_print_time_remaining","description":"Use Slic3r PE M73 time remaining","enabled":false}],"enableOctoPrintAnalyzer":false,"exactDurations":true},"TerminalCommands":{"controls":[{"commands":"M503","name":"M503 (Retrieve E-Steps etc.)"},{"commands":"G91","name":"Relative Extrusion"},{"commands":"M500","name":"Save to EEPROM"},{"commands":"G1 E100 F100","name":"Extrude 100mm"}]},"action_command_prompt":{"command":"M876","enable":"detected","enable_emergency_sending":true,"enable_signal_support":true},"announcements":{"channel_order":["_important","_releases","_blog","_plugins","_octopi"],"channels":{"_blog":{"description":"Development news, community spotlights, OctoPrint On Air episodes and more from the official OctoBlog.","name":"On the OctoBlog","priority":2,"read_until":1593102540,"type":"rss","url":"https://octoprint.org/feeds/octoblog.xml"},"_important":{"description":"Important announcements about OctoPrint.","name":"Important Announcements","priority":1,"read_until":1521111600,"type":"rss","url":"https://octoprint.org/feeds/important.xml"},"_octopi":{"description":"News around OctoPi, the Raspberry Pi image including OctoPrint.","name":"OctoPi News","priority":2,"read_until":1573722900,"type":"rss","url":"https://octoprint.org/feeds/octopi.xml"},"_plugins":{"description":"Announcements of new plugins released on the official Plugin Repository.","name":"New Plugins in the Repository","priority":2,"read_until":1593838800,"type":"rss","url":"https://plugins.octoprint.org/feed.xml"},"_releases":{"description":"Announcements of new releases and release candidates of OctoPrint.","name":"Release Announcements","priority":2,"read_until":1583322300,"type":"rss","url":"https://octoprint.org/feeds/releases.xml"}},"display_limit":3,"enabled_channels":["_octopi","_plugins","_releases","_blog"],"forced_channels":["_important"],"summary_limit":300,"ttl":360},"bedlevelvisualizer":{"command":"G28\nM155 S30\n@BEDLEVELVISUALIZER\nG29 T\nM155 S3\nM500","commands":[],"debug_logging":false,"descending_x":false,"descending_y":false,"flipX":false,"flipY":false,"ignore_correction_matrix":false,"imperial":false,"mesh_timestamp":"04/07/2020, 13:34:08","mesh_unit":1,"reverse":false,"rotation":0,"save_mesh":true,"screw_hub":0.5,"show_labels":true,"show_webcam":false,"showdegree":false,"stored_mesh":[["-0.145","-0.060","-0.000","+0.080","+0.122"],["-0.215","-0.120","-0.040","+0.055","+0.110"],["-0.205","-0.108","-0.005","+0.105","+0.177"],["-0.130","-0.028","+0.040","+0.132","+0.172"],["-0.020","+0.022","+0.082","+0.145","+0.182"]],"stored_mesh_x":[0,55,110,165,220],"stored_mesh_y":[0,55,110,165,220],"stored_mesh_z_height":250,"stripFirst":false,"timeout":1800,"use_center_origin":false,"use_relative_offsets":false},"costestimation":{"costOfElectricity":0.25,"costOfFilament":"10","currency":"\u00a3","currencyFormat":"%v %s","densityOfFilament":1.32,"diameterOfFilament":1.75,"lifespanOfPrinter":0,"maintenanceCosts":0,"powerConsumption":0.2,"priceOfPrinter":0,"requiresLogin":false,"useFilamentManager":true,"weightOfFilament":1000},"discordremote":{"allow_scripts":false,"allowed_gcode":"","baseurl":"http://octopi.local","bottoken":"NzE3MDYzNzI0ODIwODU2OTE1.XtU4KQ.hkUVjdXGssTNq65XU2m17Fp4HxU","channelid":"717063537410965564","events":{"printer_state_error":{"enabled":true,"message":"\u26a0\ufe0f Your printer is in an erroneous state.","name":"Printer state : error","with_snapshot":false},"printer_state_operational":{"enabled":true,"message":"\u2705 Your printer is operational.","name":"Printer state : operational","with_snapshot":false},"printer_state_unknown":{"enabled":true,"message":"\u2754 Your printer is in an unknown state.","name":"Printer state : unknown","with_snapshot":false},"printing_cancelled":{"enabled":true,"message":"\ud83d\uded1 The printing was stopped.","name":"Printing process : cancelled","with_snapshot":true},"printing_done":{"enabled":true,"message":"\ud83d\udc4d Printing is done! Took about {time_formatted}","name":"Printing process : done","with_snapshot":true},"printing_failed":{"enabled":true,"message":"\ud83d\udc4e Printing has failed! :(","name":"Printing process : failed","with_snapshot":true},"printing_paused":{"enabled":true,"message":"\u23f8\ufe0f The printing was paused.","name":"Printing process : paused","with_snapshot":true},"printing_progress":{"enabled":true,"message":"\ud83d\udce2 Printing is at {progress}%","name":"Printing progress (Percentage)","step":10,"with_snapshot":true},"printing_progress_periodic":{"enabled":false,"message":"\ud83d\udce2 Printing is at {progress}%","name":"Printing progress (Periodic)","period":300,"with_snapshot":true},"printing_resumed":{"enabled":true,"message":"\u25b6\ufe0f The printing was resumed.","name":"Printing process : resumed","with_snapshot":true},"printing_started":{"enabled":true,"message":"\ud83d\udda8\ufe0f I've started printing {path}","name":"Printing process : started","with_snapshot":true},"shutdown":{"enabled":true,"message":"\ud83d\udca4 Going to bed now!","name":"Octoprint Shutdown","with_snapshot":false},"startup":{"enabled":true,"message":"\u23f0 I just woke up! What are we gonna print today?\nLocal IP: {ipaddr} External IP: {externaddr}","name":"Octoprint Startup","with_snapshot":false},"test":{}},"hostname":"YOUR.HOST.NAME","permissions":{"1":{"commands":"*","users":"471966848196542468"},"2":{"commands":"","users":""},"3":{"commands":"","users":""},"4":{"commands":"","users":""},"5":{"commands":"","users":""}},"prefix":"/","script_after":"","script_before":"","show_external_ip":"auto","show_local_ip":"auto","use_hostname":false,"use_hostname_only":false},"discovery":{"httpPassword":null,"httpUsername":null,"model":{"description":null,"name":null,"number":null,"serial":null,"url":null,"vendor":null,"vendorUrl":null},"pathPrefix":null,"publicHost":null,"publicPort":80,"upnpUuid":"4d2dda8f-de3c-416a-a75b-17d13ee705d0","zeroConf":[]},"dragon_order":{"navbar_order":[],"sidebar_order":[],"tab_order":[]},"errortracking":{"enabled":true,"enabled_unreleased":false,"unique_id":"f2116399-b570-41f7-b02c-282174cfd88f","url_coreui":"https://dccc2e2f3c6b4adda72f376bbb7fe561@sentry.io/1374096","url_server":"https://2e668ba966024cfc962ba97eef89dc15@sentry.io/1373987"},"excluderegion":{"atCommandActions":[{"action":"enable_exclusion","command":"ExcludeRegion","description":"Default action to enable exclusion","parameterPattern":"^\\s*(enable|on)(\\s|$)"},{"action":"disable_exclusion","command":"ExcludeRegion","description":"Default action to disable exclusion","parameterPattern":"^\\s*(disable|off)(\\s|$)"}],"clearRegionsAfterPrintFinishes":true,"enteringExcludedRegionGcode":null,"exitingExcludedRegionGcode":null,"extendedExcludeGcodes":[{"description":"Ignore all dwell commands in an excluded area to reduce delays while excluding","gcode":"G4","mode":"exclude"},{"description":"Record default acceleration changes while excluding and apply the most recent values in a single command after exiting the excluded area","gcode":"M204","mode":"merge"},{"description":"Record advanced setting changes while excluding and apply the most recent values in a single command after exiting the excluded area","gcode":"M205","mode":"merge"}],"loggingMode":"octoprint","mayShrinkRegionsWhilePrinting":true},"filamentmanager":{"autoPause":true,"confirmSpoolSelection":false,"currencySymbol":"\u00a3","database":{"clientID":"9dbbd2d2-7757-11ea-b90d-a5a354176ba1","name":"","password":"","uri":"postgresql://","useExternal":false,"user":""},"enableOdometer":true,"enableWarning":true,"pauseThreshold":100},"floatingnavbar":{"buffer_size":"20"},"navbartemp":{"cmd":"","cmd_name":"","displayRaspiTemp":false,"makeMoreRoom":false,"piSocTypes":["BCM2708","BCM2709","BCM2835"],"soc_name":"SoC","useShortNames":false},"octolapse":{"load":null,"restore_default_settings":null,"version":"0.4.0"},"pi_support":{"vcgencmd_throttle_check_command":"/usr/bin/vcgencmd get_throttled","vcgencmd_throttle_check_enabled":true},"pluginmanager":{"confirm_disable":false,"dependency_links":false,"hidden":[],"ignore_throttled":false,"notices":"https://plugins.octoprint.org/notices.json","notices_ttl":360,"pip_args":null,"pip_force_user":true,"repository":"https://plugins.octoprint.org/plugins.json","repository_ttl":1440},"softwareupdate":{"cache_ttl":1440,"ignore_throttled":false,"notify_users":true,"octoprint_branch_mappings":[{"branch":"master","commitish":["master"],"name":"Stable"},{"branch":"rc/maintenance","commitish":["rc/maintenance"],"name":"Maintenance RCs"},{"branch":"rc/devel","commitish":["rc/maintenance","rc/devel"],"name":"Devel RCs"}],"octoprint_checkout_folder":null,"octoprint_method":"pip","octoprint_pip_target":"https://github.com/foosel/OctoPrint/archive/{target_version}.zip","octoprint_release_channel":"master","octoprint_tracked_branch":null,"octoprint_type":"github_release","pip_command":null,"pip_enable_check":false},"themeify":{"color":[{"deletable":false,"enabled":false,"rule":"background","selector":".navbar-inner","value":"#2f3136"}],"customRules":[{"enabled":false,"rule":"background-color","selector":".navbar-inner","value":"#2f3136"},{"enabled":false,"rule":"background-color","selector":".accordion","value":"#2f3136"},{"enabled":true,"rule":"width","selector":".span8","value":"70%"},{"enabled":true,"rule":"width","selector":".container","value":"100%"},{"enabled":true,"rule":"width","selector":".span4","value":"25%"},{"enabled":true,"rule":"margin-left","selector":".row","value":"0"}],"enableCustomization":true,"enabled":true,"tabs":{"enableIcons":false,"icons":[{"domId":"#temp_link","enabled":true,"faIcon":"fa fa-line-chart"},{"domId":"#control_link","enabled":true,"faIcon":"fa fa-gamepad"},{"domId":"#gcode_link","enabled":true,"faIcon":"fa fa-object-ungroup"},{"domId":"#term_link","enabled":true,"faIcon":"fa fa-terminal"}]},"theme":"discoranged"},"tracking":{"enabled":true,"events":{"commerror":true,"plugin":true,"pong":true,"printer":true,"printer_safety_check":true,"printjob":true,"slicing":true,"startup":true,"throttled":true,"update":true},"ping":null,"pong":86400,"server":null,"unique_id":"a65cc2b5-be58-4fd2-953d-4a3f28b1b593"}},"printer":{"defaultExtrusionLength":5},"scripts":{"gcode":{"afterPrintCancelled":"; disable motors\nM84\n\n;disable all heaters\n{% snippet 'disable_hotends' %}\n{% snippet 'disable_bed' %}\n;disable fan\nM106 S0","snippets/disable_bed":"{% if printer_profile.heatedBed %}M140 S0\n{% endif %}","snippets/disable_hotends":"{% if printer_profile.extruder.sharedNozzle %}M104 T0 S0\n{% else %}{% for tool in range(printer_profile.extruder.count) %}M104 T{{ tool }} S0\n{% endfor %}{% endif %}"}},"serial":{"abortHeatupOnCancel":true,"ackMax":1,"additionalBaudrates":[],"additionalPorts":[],"alwaysSendChecksum":false,"autoconnect":true,"baudrate":115200,"baudrateOptions":[250000,230400,115200,57600,38400,19200,9600],"blockWhileDwelling":false,"blockedCommands":["M0","M1"],"capAutoreportSdStatus":true,"capAutoreportTemp":true,"capBusyProtocol":true,"capEmergencyParser":true,"checksumRequiringCommands":["M110"],"disconnectOnErrors":true,"emergencyCommands":["M112","M108","M410"],"exclusive":true,"externalHeatupDetection":true,"firmwareDetection":true,"helloCommand":"M110 N0","ignoreErrorsFromFirmware":false,"ignoreIdenticalResends":false,"log":true,"logPositionOnCancel":false,"logPositionOnPause":true,"longRunningCommands":["G4","G28","G29","G30","G32","M400","M226","M600"],"maxTimeoutsIdle":2,"maxTimeoutsLong":5,"maxTimeoutsPrinting":5,"neverSendChecksum":false,"pausingCommands":["M0","M1","M25"],"port":null,"portOptions":["/dev/ttyACM0"],"repetierTargetTemp":false,"sdAlwaysAvailable":false,"sdRelativePath":false,"sendM112OnError":true,"supportResendsWithoutOk":"detect","swallowOkAfterResend":true,"timeoutBaudrateDetectionPause":1.0,"timeoutCommunication":30.0,"timeoutCommunicationBusy":3.0,"timeoutConnection":10.0,"timeoutDetection":1.0,"timeoutPositionLogWait":10.0,"timeoutSdStatus":1.0,"timeoutSdStatusAutoreport":1.0,"timeoutTemperature":5.0,"timeoutTemperatureAutoreport":2.0,"timeoutTemperatureTargetSet":2.0,"triggerOkForM29":true,"useParityWorkaround":"detect","waitForStart":false},"server":{"allowFraming":false,"commands":{"serverRestartCommand":"sudo service octoprint restart","systemRestartCommand":"sudo shutdown -r now","systemShutdownCommand":"sudo shutdown -h now"},"diskspace":{"critical":209715200,"warning":524288000},"onlineCheck":{"enabled":true,"host":"8.8.8.8","interval":30,"port":53},"pluginBlacklist":{"enabled":true,"ttl":15,"url":"https://plugins.octoprint.org/blacklist.json"}},"system":{"actions":[],"events":null},"temperature":{"cutoff":30,"profiles":[{"bed":100,"chamber":null,"extruder":210,"name":"ABS"},{"bed":60,"chamber":null,"extruder":205,"name":"PLA"}],"sendAutomatically":true,"sendAutomaticallyAfter":1},"terminalFilters":[{"name":"Suppress temperature messages","regex":"(Send: (N\\d+\\s+)?M105)|(Recv:\\s+(ok\\s+((P|B|N)\\d+\\s+)*)?(B|T\\d*):\\d+)"},{"name":"Suppress SD status messages","regex":"(Send: (N\\d+\\s+)?M27)|(Recv: SD printing byte)|(Recv: Not SD printing)"},{"name":"Suppress wait responses","regex":"Recv: wait"}],"webcam":{"bitrate":"10000k","ffmpegPath":"/usr/bin/ffmpeg","ffmpegThreads":1,"ffmpegVideoCodec":"mpeg2video","flipH":true,"flipV":true,"rotate90":false,"snapshotSslValidation":true,"snapshotTimeout":10,"snapshotUrl":"http://localhost:8080/?action=snapshot","streamRatio":"4:3","streamTimeout":5,"streamUrl":"/webcam/?action=stream","timelapseEnabled":true,"watermark":false,"webcamEnabled":true}}

**Comment by fieldOfView** [comment]
I can't reproduce this with the current version of Cura. I refactored the camera handling to clean up the code and support multiple cameras a little while ago. Could you test this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/OctoPrintPlugin/JplGzXeqTmvItgk-5_Ee7zb_iQLS7WR6dowqxU91AGGZ/OctoPrintPlugin-v7.0.0-2020-07-03T10%3A06%3A19Z.curapackage?Expires=1909406505&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=UXcQDNfZ8r4RPqn0As5UAyGvFSjPXKQjtk9AX2PPGJavNkNmu8ls3q6ccamNe4c01yDjHwW3%2FUXyzlVh3hKVgRXmZ6hfhVTA4KW0JXdGmmA3GPN4V0MpkcIiR5EjmyEW6y8b5uJJL0vbr4tISsNiTUUzPVBzOIP4ykZRWctF2R8jKHG1ifeNesfQ4syl2l2T%2FfTtIG%2BFvIcOaOBlfQUa2Mqaq27cXioFhveQypWehiUfGONYh2sxEcorV%2BpLR8mnaDk6xiMXJF%2FdzgCH1hBc6c%2F6JvhaxbFhbG5pVLXPVPV9oOQkZ2Lu6Lw2ErNflfxt%2B0VzYaGIzbRVq5vCVF3ZHQ%3D%3D)? Download the file, and drop it onto the buildplate in Cura as if you were opening a 3d model through drag and drop.

**Comment by JamieS01** [comment]
Seems to be working with that snapshot! Is there any other information that I can provide which may help?
![Screenshot (31)](https://user-images.githubusercontent.com/60047145/86630001-2268a500-bfc4-11ea-8b9c-f6cf0a2404dc.png)

**Comment by fieldOfView** [comment]
> Seems to be working with that snapshot!

![I See This as an Absolute Win](https://i.kym-cdn.com/entries/icons/original/000/029/623/cover16.jpg)

Well, it seems I am going in the right direction then. I will add a "fixed" label to this issue, but will keep the issue open until a version containing this fix is available in the Marketplace.
