### ISSUE TITLE
Crash when webcam's streamUrl is None

### ISSUE THREAD

**Issue by Ghostkeeper** [fieldOfView/Cura-OctoPrintPlugin#181]
Hi,

We're seeing this crash report crop up a couple of times, since today: https://sentry.io/share/issue/f56f8c9106d04fc2959230c7db6d363c/

It seems that the webcam data has a `streamUrl` entry that is set to `None`. The "strip" function then doesn't work and crashes Cura. Maybe this needs to have a check for `None` which sets it to an empty string then?
I don't know where the `None` comes from though; perhaps that is where the problem lies.

**Comment by Ghostkeeper** [comment]
Since that sharing link is not as expansive as what the developers can see, here is a screenshot of some more information:
![image](https://user-images.githubusercontent.com/2448634/87776400-023caf80-c828-11ea-8201-99c1bbb1a314.png)

And we also get a traceback:
![image](https://user-images.githubusercontent.com/2448634/87776543-3ca64c80-c828-11ea-87ac-a6fed7604118.png)

This was seen 16 times so far.

**Comment by fieldOfView** [comment]
Thanks for the report. I can see how this happens, and it is easy to fix. Very unfortunate that it slipped through testing. Do you think it is worth pulling the plugin from the marketplace over?

**Comment by fieldOfView** [comment]
I have submitted a fixed version to the Marketplace.
