### ISSUE TITLE
Build fails because OctoPrintPowerPlugins.py was renamed

### ISSUE THREAD

**Issue by DarkShortie** [fieldOfView/Cura-OctoPrintPlugin#184]
The build fails because OctoPrintPowerPlugins.py was renamed to PowerPlugins.py but in CMakeLists.txt the old name is still mentioned: https://github.com/fieldOfView/Cura-OctoPrintPlugin/blob/8affa8aa9796cb37129d3b7222fff03f86c936cd/CMakeLists.txt#L10

**Comment by fieldOfView** [comment]
Good catch. Fixed in master in 5a62355

**Comment by DarkShortie** [comment]
Thanks, works

**Comment by fieldOfView** [comment]
I like to keep issues open until a new release is available on the Ultimaker Marketplace.
