### ISSUE TITLE
Folder support

### ISSUE THREAD

**Issue by ollien** [fieldOfView/Cura-OctoPrintPlugin#186]
One of the features I like about the PrusaSlicer octoprint feature is that I can send all of my uploads to an "uploads" folder to at least separate my uploaded prints from my sorted ones. It would be super cool if I could set a default upload location for this plugin. 

Happy to make a PR for it myself, just don't wanna make it if you're totally opposed to the concept :)

**Comment by fieldOfView** [comment]
If you install the "Custom Printjob Naming" plugin, you can configure a path via that plugin:
https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/CustomJobPrefix

The path configured via that plugin can even have several replacement patterns in it, if you wish.

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/28

**Comment by ollien** [comment]
Oh neat. Sorry, can't believe I didn't see that issue. Thanks :)
