### ISSUE TITLE
'NoneType' has no object 'state'

### ISSUE THREAD

**Issue by sdaitzman** [fieldOfView/Cura-OctoPrintPlugin#192]
![image](https://user-images.githubusercontent.com/1499476/93714456-c75d3d80-fb30-11ea-8acc-6c1a1b7a4a2c.jpeg)

This sometimes happens when I submit a print. Is there any other useful debug info I can provide?

Most recent versions of Cura and Octoprint are running.

**Comment by fieldOfView** [comment]
A cura.log would be helpful; see Help -> Show configuration files. It would be nice if you could indicate an approximate time/dat of this happening, so I can find that moment back in the logs.

**Comment by fieldOfView** [comment]
@sdaitzman I cannot fix this without further information requested above.

**Comment by sdaitzman** [comment]
@fieldOfView thanks for the reminder! I dug more into the issue, and it turns out the true issue is that my RasPi's WiFi driver is crashing, knocking it off the local net.

Perhaps this is expected behavior, then, for when the Octoprint instance disappears? If so, I guess this issue is closed or repurposed as a feature request (to display a warning that the Octoprint instance was not found, rather than this error message).

**Comment by fieldOfView** [comment]
> Perhaps this is expected behavior, then, for when the Octoprint instance disappears?

The error message is not expected behavior. The upload failing when the OctoPrint instance disappears would interrupt things through. Thanks for this extra bit of information,

**Comment by fieldOfView** [comment]
For reference: https://community.ultimaker.com/topic/34388-nonetype-object-has-no-attribute-close-in-cura-71/?do=findComment&comment=274633

**Comment by fieldOfView** [comment]
This should be fixed in master

**Comment by fieldOfView** [comment]
A new version including a fix for this issue is available from the Marketplace.
