### ISSUE TITLE
Octoprint plugin does not honour Select print job after uploading

### ISSUE THREAD

**Issue by MaxwellSmartAgent-86** [fieldOfView/Cura-OctoPrintPlugin#195]
The checkbox Select print job after uploading seems to be completely ignored.

This has been happening since I installed Cura 4.7.0.  When I send a job to the printer, I receive a message (warning?) that the job could not be selected as the printer is printing.

The job still gets uploaded fine so it's not a big deal but I just find it a little annoying.  Of course, if the printer is idle obviously I don't see that message.

I have NOT checked to see if any other checkboxes in the settings are similarly affected.

**Comment by fieldOfView** [comment]
Sounds related to https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/187

I'll look into it.

**Comment by NoHow81** [comment]
I can confirm this behavior with Cura 4.4 and 4.7

**Comment by fieldOfView** [comment]
Should be fixed in 8354ce0

**Comment by fieldOfView** [comment]
A new version including a fix for this issue is available from the Marketplace.
