### ISSUE TITLE
Choose a folder tree on octoprint when uploading

### ISSUE THREAD

**Issue by Turiok** [fieldOfView/Cura-OctoPrintPlugin#199]
Hi,

I love this plugin.
We are a fablab with many users.
Each user has its own folder in octoprint.
It'll be great to have the choose of folder to upload the gcode.

Maybe a global folder in the configuration panel.
Or when clicking on "Print with octoprint " a popup to choose the folder name.

Tks for this plugin

**Comment by fieldOfView** [comment]
Installing the Custom Printjob Name plugin from the Marketplace will get you some of this functionality, though it does not get you a dropdown list of current folders.

See also https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/28

**Comment by fieldOfView** [comment]
> And a last feature.

Please don't include multiple features in a single issue; these are impossible to keep track of. Could you open an additional issue for this?

**Comment by Turiok** [comment]
I delete the other asking feature to have the name of the printers in the button.

I forget the name of the printer is written at the top of the window.
So it's not necessary to add this information on the button. 

Sorry

**Comment by Turiok** [comment]
Hello,

I'm beginning to look at this feature.
I find here it is possible : https://docs.octoprint.org/en/master/api/files.html#upload-file-or-create-folder
And I tried with curl and it is working.
But I'm very beginner to python and It seems to difficult to me to create a PR for this.

**Comment by fieldOfView** [comment]
The next version of the plugin will have an optional dialog to confirm the jobname, and more relevantly for this issue a path to store the job.

Please help me test this feature by downloading this [development snapshot](https://storage.googleapis.com/um-cloud-production-cura-packages/v1/packages/OctoPrintPlugin/FF_CBKkntJes5ApbMoHWqgklxPoLeubdesoMFX62xHHo/OctoPrintPlugin-v7.0.0-2021-11-09T17%3A14%3A47Z.curapackage?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=cura-packages-api%40um-cloud-production.iam.gserviceaccount.com%2F20211109%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211109T171503Z&X-Goog-Expires=604800&X-Goog-SignedHeaders=host&X-Goog-Signature=68c6272055900f6c5a7db3a029fc54ba8adb7e90b0a3bd0ac52b071b036aa76b04af2b5a0aab494f6c1c93aadf13c3fcb8bce93635439121b1ad52d64c053cff767bf336edec6e2cb40a3f10b72d871f67dc983f351e842ae7f7da6d08d93cf9aa99ffc2f15abc9f5414dc295b08c42d3973c924fd4ddc8f1b05ead5562ee471effa9890234e09003eb244fbfe47fde9a295fdb21eae4bfcb7fc59169761747e8f4a102fde5232c91f0f0242fa43a1de2f5944c9045bb95fa4469cb3fcb3c41c2ed5e27f74d686c5ca2da373e95ddedfb146f6fbb874b7c9f4fc8617fabd2d3ad6b91f9be68183d7e712f781aac7dbe17e00df479378392513976c2d5b412548) and dropping it on the Cura buildplate to install it. The option can be found in the Connect to OctoPrint dialog.

**Comment by Turiok** [comment]
Hi @fieldOfView ,

I tried the plugin. It works great! Thank you.
I tried with Cura 4.11.

When the file is uploaded. A popup is displayed in Cura with the filename. I think the path should be added to the filename.
And I think the upload should be enabled even if the printer is disconnected from Octoprint.
In our case, users upload from internet the file on Octoprint. And when they are in the fablab, they launch the print.
So during the upload it's often the printer is not turned on.

A possible improvement will be to display the actual file structure if its possible but it's already awesome to have this feature.

**Comment by fieldOfView** [comment]
> A popup is displayed in Cura with the filename. I think the path should be added to the filename.

Fixed in efb4b66

> And I think the upload should be enabled even if the printer is disconnected from Octoprint.

That is a different issue, but this should already be possible. As long as I don't select the option to start printing after upload, the  file is uploaded regardless of whether a printer is connected.

> A possible improvement will be to display the actual file structure if its possible

I saw that request coming. Could you open a new issue for that?
In the mean time, you may also be interested in the "Printjob Naming" plugin which lets you preconfigure a path.

**Comment by Turiok** [comment]
Hi, 

Do you want another issue for the disconnected part too?

I created the issue to see the filesystem : #253

**Comment by fieldOfView** [comment]
>Do you want another issue for the disconnected part too?

Yes, please. Please include both your cura.log (see help->show configuration folder) and OctoPrint logs.
