### ISSUE TITLE
OctoPrint not configurable for QIDI printers

### ISSUE THREAD

**Issue by joekhoobyar** [fieldOfView/Cura-OctoPrintPlugin#201]
I can only get the OctoPrint configuration options if I add my QIDI printer as a generic printer.

I would like be able to configure my QIDI printer using the same profiles that came with QIDIPrint, even if I am not using it to print to.  Then, just print to it using OctoPrint.

Is that something that can even be fixed?

**Comment by fieldOfView** [comment]
Ultimaker Cura does not seem to come with definitions for the QIDI printer, does it? So how do you add your printer to Cura, if not as a Custom FFF Printer?

**Comment by fieldOfView** [comment]
Unless you answer my questions, there is nothing I can do for you.
