### ISSUE TITLE
Support for prettygcode plugin

### ISSUE THREAD

**Issue by SirDumb** [fieldOfView/Cura-OctoPrintPlugin#202]
While I don't care about the camera, I'd love to see at which point exactly is the print.
No idea how this would be possible without any octoprint plugins but prettygcode provides 
<octoprint ip>/?fullscreen=1#tab_plugin_prettygcode
so all that is needed is a browser view, although I this might be harder than I think it is.

**Comment by fieldOfView** [comment]
Unfortunately there is no way to include a webview inside Cura.
