### ISSUE TITLE
Can't find the plugin in the Marketplace when logged in.

### ISSUE THREAD

**Issue by r1b1n** [fieldOfView/Cura-OctoPrintPlugin#204]
I can't find it in the marketplace and as soon as I log in in the browser it's also gone.

**Comment by fieldOfView** [comment]
The cloud backend seems to have marked your account as an "Essentials" user. 
https://ultimaker.com/software/ultimaker-essentials
Essentials users pay for the privilege to get fewer plugins available to them, under the guise of being more secure.

If you have not subscribed to Ultimaker Essentials, could you let me know your Ultimaker account name, so I can tell the people that manage the Ultimaker accounts that they screwed up _again_ and fix it for you?

**Comment by fieldOfView** [comment]
Note that this is not limited to Cura 4.8. Previous versions behave the same way.

**Comment by fieldOfView** [comment]
As a workaround, you can log out of your account in Cura, then install the plugin, and if you wish you can log in again.

**Comment by r1b1n** [comment]
Thanks for the really quick advice, logging out worked.

I have not subscribed to essentials and don't want to.
Octoprint worked until I updated to 4.8, that's why I assumed this as the reason.

**Comment by r1b1n** [comment]
Oh and my account name is rob223
