### ISSUE TITLE
Do i need a delay to powerup the printer ?

### ISSUE THREAD

**Issue by epalzeolithe** [fieldOfView/Cura-OctoPrintPlugin#223]
Hi

you do a great job !

Well, im using CURA+TPLINK in octoprint to power the printer and your plugin.

Well, it sends well the file to octoprint, and powerup the printer.

But sometimes, the print job start, sometimes not, i need to go to octoprint ti launch the print (file already loaded)

Its a bug ? Or perhaps i need some delay to powerup properly the printer, and the plugin tries to launch the print before the connexion is properly made between octoprint and the printer ?

Thanks in advance :)

**Comment by fieldOfView** [comment]
I need logs from both Cura and OctoPrint, with a timestamp of where this issue occurred.

**Comment by fieldOfView** [comment]
Closing this issue due to lack of info
