### ISSUE TITLE
Turn on printer with grayed out

### ISSUE THREAD

**Issue by ingo916** [fieldOfView/Cura-OctoPrintPlugin#226]
How do I enable this feature? I have the TP-Link plugin and its working with Octoprint.
OctoPrint 1.5.3
Python 3.7.3
OctoPi 0.18.0
TP-Link Smartplug (0.9.26)

![image](https://user-images.githubusercontent.com/41309095/106314116-1ec99380-621e-11eb-9bd8-feb8c7a17a0b.png)

**Comment by ingo916** [comment]
i had to enable start print jog after uploading, is there a way to to turn on the printer without starting the print job?

**Comment by fieldOfView** [comment]
> i had to enable start print jog after uploading

Indeed, that is the design. Why would you want the plugin to turn on the printer if you don't want the plugin to start the print? If you want to manually start the print, can't you also manually power on the printer?
