### ISSUE TITLE
Cura sending job to the wrong OctoPrint instance

### ISSUE THREAD

**Issue by orangeworx** [fieldOfView/Cura-OctoPrintPlugin#235]
Hey there,
This behavior started as I updated Cura to 4.9.1. It all started when I was swapping between printers to send a single job to each of them. No matter what I did, Cura/Plugin was sending the print to the 2nd instance, I forced closed everything and have had the issue persistently.
I have 2 printers that worked well with the OctoPrint plugin. No issues to get them recognized, requesting API keys etc...
Since the update, for some bizarre reason, my settings crapped out... Tried to revert to a backup I had (on 4.8.0) and resetting config (popup I was getting on opening Cura) to no avail.
Basically, when I go to manage the printers and select Connect OctoPrint, both instances are properly discovered.
There's one major issue though; 1 instance behaves normally, I can request the key (with button or through Octoprint) and it works, the other instance has no request button, the "open in browser" does load OctoPrint web interface but keys do no work (The API key is not valid... error message)

I tried updating Raspberry/OctoPrint/remove-reinstall plugin, different keys, turning off the working instance to see if that's affecting the 2nd one. A little confusing to say the least.
Please advise if this is not clear or if there's anything I can provide to help figuring out what's going on...

Thanks for taking the time to create this plugin and support it...

**Comment by fieldOfView** [comment]
I need logs. See Help -> Show configuration folder, and locate the Cura.log file. Post that somewhere and post a link here.
