### ISSUE TITLE
webcam not appearing

### ISSUE THREAD

**Issue by elA2papi** [fieldOfView/Cura-OctoPrintPlugin#238]
hey fieldOfView,

I see this has been an issue in the past. I tried adding the printer manually via the IP address as was suggested in previous fixes, but it didn't work. I'm using Cura 4.9.1. The webcam appears in Octoprint. I mentions of posting logs, but I don't know how to do that. Any suggestions?

Thanks in advance...

**Comment by fieldOfView** [comment]
I can't do anything without (full) logs. Go to Help -> Show configuration folder, and in the folder that opens locate Cura.log. Post that file somewhere and post a link here (dropbox, google drive, pastebin, etc).

**Comment by fieldOfView** [comment]
Closing due to lack of information.
