### ISSUE TITLE
Camera rotation or flip

### ISSUE THREAD

**Issue by fredlamour** [fieldOfView/Cura-OctoPrintPlugin#242]
Hi,
Is there a way to retrieve the setting from Octoprint regarding camera rotate or flip so the image is correctly displayed in Cura ?
thanks;

**Comment by fieldOfView** [comment]
The camera rotation and flip settings have been supported for quite a while. What version of the plugin are you using?

**Comment by fredlamour** [comment]
Hi,

I have uninstalled the plugin and reboot. After new install the image is correct.
thanks.
