### ISSUE TITLE
No camera in Cura

### ISSUE THREAD

**Issue by bASHer91** [fieldOfView/Cura-OctoPrintPlugin#250]
Been having this issue for a while. In the monitor tab, webcam is no longer displayed. How do i get it back? Camera ip address is correct and works in apps like Printoid.

**Comment by fieldOfView** [comment]
Please post a link to your cura.log, which can be found via Help -> Show configuration folder...

**Comment by bASHer91** [comment]
[cura.log](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/7449331/cura.log)

**Comment by bASHer91** [comment]
ive sorted it after looking at the log.

Webcam stream was missing the http://octopi.local/ on octoprint.

**Comment by fieldOfView** [comment]
Alternatively to adding `http://octopi.local/` you could also just add the `/` in front of the stream url.
