### ISSUE TITLE
OctoPrint not showing on 4.12.1

### ISSUE THREAD

**Issue by Axsimulate** [fieldOfView/Cura-OctoPrintPlugin#258]
I clicked on Add to Cura in the Marketplace, restarted Cura like it said, no luck.

**Comment by fieldOfView** [comment]
Have you read the instructions in the readme?
https://github.com/fieldOfView/Cura-OctoPrintPlugin#how-to-use

**Comment by fieldOfView** [comment]
I cannot help you if you don't answer my question.

Where do you expect the plugin to show up?

**Comment by Axsimulate** [comment]
Sorry! I got it working. It seems like I had to manually add the plug-in then add it with the Marketplace. Then after a restart of Cura it detected it.
