### ISSUE TITLE
No option 'Connect to octoprint'

### ISSUE THREAD

**Issue by Bristol-SuShuo** [fieldOfView/Cura-OctoPrintPlugin#265]
Application version
4.13.1

Platform 
Windows 10

Question
I don't have the option "Connect octoprint". I have checked the log and this plugin is loaded when I start Cura. I have also tried different versions, but they all don't work.
<img width="551" alt="1645113300" src="https://user-images.githubusercontent.com/91885040/154519323-f21ba4a1-15ed-47ad-b20e-fa55f8d91197.png">

Log
[cura.log](https://github.com/fieldOfView/Cura-OctoPrintPlugin/files/8090119/cura.log)

**Comment by fieldOfView** [comment]
The Ultimaker S3 can not be connected to or controlled with OctoPrint.
