### ISSUE TITLE
OctoPrintPlugin using wrong IP address

### ISSUE THREAD

**Issue by zifnab0** [fieldOfView/Cura-OctoPrintPlugin#266]
It seems that the plugin is choosing the "wrong" IP address from the zeroconf list. Is there a way to help the plugin make a better choice ? :-)
Or should it be filtered on octoprint side ?

In Cura :
![image](https://user-images.githubusercontent.com/50694607/156654577-6368b63b-ecb3-4208-938b-72d10c7a5a82.png)

```
$ if config -a
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255


wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.65  netmask 255.255.255.0  broadcast 192.168.0.255
```

from octoprint point of view :
```
>>> import octoprint.util.net
>>> list(octoprint.util.net.interface_addresses())
['192.168.0.65', '172.17.0.1']
```

**Comment by zifnab0** [comment]
Actually what puzzles me is that this behaviour is random. Most of the time, the good address is used. When I reboot the Pi it usually fixes the issue, but after a while it switches  (!?!).
I will open a feature request on octoprint to suggest to filter out (at least) docker IP adress from reported IP addresses.

**Comment by zifnab0** [comment]
The answer is here : https://docs.octoprint.org/en/master/bundledplugins/discovery.html. The discovery plugin can be tuned as required.

**Comment by fieldOfView** [comment]
Thanks!
