### ISSUE TITLE
Prints not starting after upload Cura 5

### ISSUE THREAD

**Issue by frankt2012** [fieldOfView/Cura-OctoPrintPlugin#271]
Prints are uploaded properly to Octoprint but are not staring automatically like they use to in Cura 4.13. Using latest octoprint plugin 3.7.0 on Cura 5.

**Comment by fieldOfView** [comment]
I am getting more reports to this effect. I'll look in to it.

**Comment by frankt2012** [comment]
> I am getting more reports to this effect. I'll look in to it.

Thank you

**Comment by fieldOfView** [comment]
Do you have Print Time Genius installed in OctoPrint?

**Comment by frankt2012** [comment]
> I think I have fixed this bug. Could you try the new .curapackage I have created here? https://github.com/fieldOfView/Cura-OctoPrintPlugin/releases/tag/v3.7.0-DEV

I will try it and report back to you. Thank you.

**Comment by frankt2012** [comment]
> I think I have fixed this bug. Could you try the new .curapackage I have created here? https://github.com/fieldOfView/Cura-OctoPrintPlugin/releases/tag/v3.7.0-DEV

I can confirm that this has fixed the issue. Actually it looks like everything is working. I am even seeing the video feed and temp readings. Thank you for the fix.

**Comment by fieldOfView** [comment]
Awesome, thanks for the quick test!
