### ISSUE TITLE
Select destination folder before sending

### ISSUE THREAD

**Issue by MiguelAngelLV** [fieldOfView/Cura-OctoPrintPlugin#28]
Would be interesting can set name and folder when upload the file.

**Comment by fieldOfView** [comment]
You can already set the name. The name that is used is shown in the lower-right corner of the viewport area (above the print time and amount estimates). Click the name there, and you can edit it.

There currently is no way to select the destination folder.

**Comment by fieldOfView** [comment]
Here's a sketch by reddit user /u/Dweller:
![](https://i.imgur.com/Mtniu3F.jpg)
src: https://old.reddit.com/r/octoprint/comments/fus9rz/best_slicer_for_octo/fmemp92/

**Comment by ChrisNava** [comment]
GUI Suggestion: Assuming it's possible to get a list of existing folders from Octoprint, just have the "Print with OctoPrint" drop-down menu list the folders under "Save to File" and perform a save when selected.  That way no GUI window change is required.

**Comment by fieldOfView** [comment]
I could see that work if a user had only one or two subfolders, but having - say - ten to twenty subfolders would get you a lot of "Print with OctoPrint to folder ...` items in that list. It would also further muddy the functionality of that split button. 

I think I'll probably do it something like this:

![image](https://user-images.githubusercontent.com/143551/80352444-32516380-8874-11ea-9c1c-cb303e6d76a2.png)

The button will dropdown a menu of available folders, and a future version may or may not have a function to create a new folder. I don't like that the "preview" button is between the print button and the folder selection dropdown button, but sometimes you have to compromise.

**Comment by fieldOfView** [comment]
I'm taking a different path, and am implementing this as part of the [Custom Job Prefix](/fieldofview/Cura-CustomJobPrefix) plugin.

**Comment by fieldOfView** [comment]
Setting a path is now implemented in the master branches of the OctoPrint Connection plugin and the Custom Job Prefix plugin.
